cmd/witness/impl/witness.go
internal/feeder/sumdb/sumdb_feeder.go
internal/feeder/sumdb/sumdb_feeder_test.go
internal/http/server.go
internal/persistence/inmemory/inmemory.go
internal/persistence/inmemory/inmemory_test.go
internal/persistence/persistence.go
internal/persistence/sql/sql.go
internal/persistence/testonly/persistence.go
internal/witness/witness.go

This may change behaviour in some situations, but almost certainly for
the better. Previously errors during finalizing operations were dropped,
and there would be no trace in the local logs if HTTP responses could
not be written.

Fixed golangci-lint errors

---

cloudbuild_docker.yaml

This is expected to run using the GCP project for transparency-dev, and output the images to artifact registry instead of the somewhat obsolete container registry.

Build omniwitness docker images using GCP

---

cmd/omniwitness/Dockerfile
cmd/witness/Dockerfile

They were referring to the old locations in trillian-examples

Dockerfiles now refer to the correct paths

---

cmd/omniwitness/Dockerfile

There was a name collision between the desired output bin file and a directory in the root of this repo called omniwitness. This change builds into /bin/omniwitness in order to avoid that collision.

Fix the docker build

---

cmd/omniwitness/docker-compose.yaml

The previous image is a stale one that was built from trillian-examples, where the new image is the one built from the latest version of the code in this repo.

Update link in docker-compose to freshest image

---

omniwitness/logs.yaml

This updates the Pixel BT log origin string from `DEFAULT` to the one now being served by the log.

Update Pixel BT log origin

---

internal/feeder/rekor/rekor_feeder.go

Rekor can now optionally return a stable checkpoint that updates every 5 minutes rather than each time a new entry is uploaded. This lets the distributor gather matching cosigned checkpoints from witnesses.

Update Rekor feeder to get stable checkpoint

---

internal/distribute/rest/distribute.go
internal/distribute/rest/distribute_test.go

The distributor wasn't using the baseURL properly and failed to send the
whole checkpoint properly. Both issues are now addressed and this change
adds a test to confirm.

Fix up the redistributor and add tests

---

.github/dependabot.yml
cmd/omniwitness/Dockerfile

Update docker images using dependabot, and pin to hashes to make sure everyone uses the same base image

Dependabot for docker

---

go.mod
go.sum
internal/feeder/feeder_test.go
internal/feeder/serverless/serverless_feeder.go

This PR updates the witness repo to follow the [graduation of `serverless` to its own repo](https://github.com/transparency-dev/serverless-log).

Follow serverless-log move

---

cloudbuild_docker_legacy.yaml

Not a single build has succeeded in months, all due to timeouts. This is a known issue that seems unlikely to be fixed given the activity on https://github.com/docker/buildx/issues/350. For the time being, disable these builds so we at least get the amd64 builds.

Disable broken armv7 builds

---

.github/workflows/go_test.yml
.github/workflows/golangci-lint.yml
go.mod
go.sum

Unblock https://github.com/transparency-dev/witness/pull/170.

Bump Go from 1.19 to 1.21

---

internal/distribute/rest/distribute.go

A PUT request that hits a redirect gets converted to a GET request to the new resource. All of the existing checks for 200 will pass, which makes it look like it distributed even though no mutation operation occurred. This is a massive trap that is way too easy to fall into.

Fail on redirect changing request method

---

client/http/witness_client.go
internal/distribute/rest/distribute.go
internal/distribute/rest/distribute_test.go
internal/feeder/pixelbt/pixel_feeder.go
internal/feeder/rekor/rekor_feeder.go
internal/feeder/serverless/serverless_feeder.go
internal/http/server.go

A redirect on a PUT request will make the http client perform a GET request to the signposted URL. This will (probably) return a 200, which the code will then interpret as a successful PUT. This check ensures that the method the response relates to is the same as the one we invoked.

Safeguard against redirects on PUT request

---

cmd/feedbastion/main.go
cmd/omniwitness/README.md
cmd/omniwitness/monolith.go
go.mod
internal/feeder/bastion/bastion_feeder.go
internal/feeder/bastion/bastion_feeder_test.go
internal/feeder/sumdb/sumdb_feeder.go
omniwitness/omniwitness.go

This PR adds:
- an initial version of a `Feeder` which knows how to interact with a `Bastion` host, as outlined in C2SP/C2SP#56.
- a simple tool to _feed_ witnesses behind a bastion.
```
❯ go run ./cmd/feedbastion --bastion_url=https://localhost:8443/8d95291650778b3c4d91c7a4b12d20877fa551c94366774f5bb484df2488c7ca/add
I0508 19:13:48.385216  472044 main.go:124] 200 OK:
— testwitness n3cVs9nAO2YAAAAACeRsjJ0gGB7IEtcCiedWMDAKooMjdNztQ73Vbp09q4IwdS011cSfjg0NmQ3XWismx/5OJSUh72rbdXgYctffDQ==
I0508 19:13:48.526615  472044 main.go:124] 200 OK:
— testwitness n3cVs9nAO2YAAAAAfYB3JUo6sCns+AynfHhAAG+u41iIZ83T8MFh+WhGDhB2l3HNBUzWWHl1GY8TzBFG9i0FzyVtc/GjplYMT0AMAw==
I0508 19:13:48.649482  472044 main.go:124] 200 OK:
— testwitness n3cVs9nAO2YAAAAArMAjHfYIo5JTd2UXV+Fe1G6kXXzM9u4A05kzccC9g2ToQuvS+mZJuvDNkqq …
```

Add initial cut of a Bastion feeder

---

cmd/omniwitness/README.md
cmd/omniwitness/docker-compose.yaml

The GitHub distributor has long since been retired. This PR cleans up
some of the traces that remained.

Removed vestigial docs and flag routing for GH

---

omniwitness/logs.yaml

Tree ID is 1193050959916656506, key remains the same

Add new shard for Rekor

---

internal/witness/witness.go
internal/witness/witness_test.go

The tests show that this worked, providing that the proof was empty. When the merkle library is updated to pull in transparency-dev/merkle#140, this will fail too. In both of the new test cases, the witness should ratchet forward when a new checkpoint is provided.
The second commit in this PR updates the witness to handle transitions forward from tree size 0 properly. The tests have been updated accordingly. Updating the Merkle library should now be possible, because we can't reach the `VerifyConsistency` call if the starting tree size is 0.
As a separate note, I recommend rewriting these tests at some near point in the future. They are currently quite brittle as they rely on hard coded test data with no obvious script to update them. An in-memory test log would be a great way to generate …

Witness properly handles ratcheting forward from tree size 0

---

go.mod
go.sum

This is primarily to pull in https://github.com/transparency-dev/merkle/pull/140 now to confirm it doesn't have any suprises while I'm still context loaded on the issue. Better that than it surprising someone down the road.

Bump merkle library to latest version

---

omniwitness/configs_test.go
omniwitness/logs_test.yaml
omniwitness/omniwitness.go

This PR allows the `omniwitness` to be configured with logs which have no associated feeder, and will consequently only be updatable via the synchronous bastion protocol.

Allow configuring bastion-only logs

---

cmd/omniwitness/README.md
cmd/omniwitness/monolith.go
omniwitness/omniwitness.go

By allowing the poll interval to be configured in the monolith, the omniwitness operator can now control how often the witness will poll logs to look for new checkpoints. This includes disabling polling, which allows the witness to be deployed in a bastion-only mode.

Log polling interval can be configured

---

internal/witness/witness.go

Removed a short circuit that previously skipped doing work if the tree at that size had previously been witnessed. Having fresh timestamps on checkpoints is a feature.

Perform witness signing on checkpoints of the same size

---

internal/feeder/feeder.go

The feeder previously short circuited if the witness had already witnessed an equivalent checkpoint. This meant that logs would get stale timestamps from the witnesses. This change makes it so that the witness will keep updating their timestamps on checkpoints.

Feeders push checkpoints even if they are equivalent

---

omniwitness/logs.yaml

Log details as per https://developers.google.com/android/binary_transparency/google1p/log_details. PEM cert converted to 1-line ecdsa public key using script at https://go.dev/play/p/4TK37wHxSjf.

Add Google System APK Transparency Log

---

.github/workflows/go_test.yml
.github/workflows/golangci-lint.yml
cmd/loadtest/loadtest.go
go.mod

Load test escalates until witness updates take longer than a deadline,
or a success criteria of updates/sec is reached. If the number of logs
allocated isn't sufficient, then it can be the case that the load test
will run forever as increasing the throttle doesn't create more load due
to updates for each log being performed consecutively.
The load test always creates deterministic logs, with the same keys and
values. On init, it speaks to the witness to set the log sizes to the
last witnessed sizes. This aids load testing as the witness state
doesn't need to be cleared before every run.
The log implementations are currently in-memory and store all hashes.
This can be replaced with a more svelte compact range version if needed,
but I backed out of this approach as generating the …

Basic load test for updating witnesses

---

cmd/omniwitness/monolith.go
omniwitness/omniwitness.go

This allows implementations to be used that don't have the key material locally, for example in a KMS. Fixes #303.

Pass in signers rather than keys into witness

---

omniwitness/logs.yaml

Used by all Andxor applications to certify integrity of application logs.
(and possibly other usages in the future)

Add Andxor transparency logs.

---

api/http.go
cmd/feedbastion/main.go
internal/feeder/bastion/bastion_feeder.go
internal/feeder/bastion/bastion_feeder_test.go
internal/feeder/feeder.go
internal/feeder/feeder_test.go
internal/http/server.go
internal/http/server_test.go
internal/witness/witness.go
internal/witness/witness_test.go
omniwitness/omniwitness.go

This PR is a deeper fix to the C2SP `tlog-witness` compliance issues, which changes the internal witness API to better match.
Also removes the call to `Update` exposed via the local HTTP server.
TODO(al): Either in here, or in a follow-up, make `Update` just return the sig rather than the whole CP.

Fix C2SP compliance and simplify

---

go.mod
go.sum
internal/http/server.go
internal/persistence/inmemory/inmemory.go
internal/persistence/inmemory/inmemory_test.go
internal/persistence/persistence.go
internal/persistence/sql/sql.go
internal/persistence/sql/sql_test.go
internal/persistence/testonly/persistence.go
internal/witness/witness.go
internal/witness/witness_test.go
omniwitness/omniwitness.go

This PR replaces the `ReadOps`/`WriteOps` structures with `Latest` and `Update`.
The `.*Ops` approach exposes the transaction to higher levels, which is a richer interface than is strictly needed.
Towards #355

[Simplify] Replace {Read,Write}Ops with Update func

---

internal/persistence/inmemory/inmemory.go
internal/persistence/persistence.go
internal/persistence/sql/sql.go

This PR removes a named type and inlines the definition where it was used.
The named type is currently making it impossible to update the AW implementation, and didn't really provide much value as the signature is small enough to inline easily.
Removing it avoids the needing to resolve opaque indirection when implementing it, and the need to type alias it into the `omniwitness` package.

Remove unnecessary named func type

---

internal/feeder/rekor_v1/rekor_feeder.go
omniwitness/omniwitness.go

Renaming this feeder to distinguish between this feeder and the upcoming Rekor v2 feeder which will simply use the tiles feeder.
Also remove fetching the stable checkpoint, since this has never actually been integrated into any workflow in practice.

Rename Rekor feeder, remove fetching stable checkpoint

---

CHANGELOG.md
README.md
cmd/omniwitness/monolith.go

With a cosignature/v2 spec on the horizon (https://github.com/C2SP/C2SP/pull/146/), I'm cleaning out the old legacy signatures. I can't see any users of these any more.
Added a CHANGELOG; we should probably tag a 1.0.0 of this repo soon.

Drop support for legacy witness sigs

---

cmd/feedwitness/main.go
internal/bastion/bastion.go
internal/config/log.go
internal/distribute/rest/distribute.go
internal/distribute/rest/distribute_test.go
internal/witness/witness.go
internal/witness/witness_test.go
omniwitness/configs.go
omniwitness/configs_test.go
omniwitness/http.go
omniwitness/http_test.go
omniwitness/omniwitness.go

This PR:
1. shifts configuration to be done mostly in terms of `config.Log` structs rather than a number of similar types in various packages.
2. hides the implementation of the configuration delivery mechanism from the things which ultimately interrogate/use that config.
This opens a path to allowing binaries using the library to store their configuration in whichever way makes most sense for them.

Hide configuration implementation

---

cmd/gcp/omniwitness/main.go
cmd/omniwitness/monolith.go
omniwitness/omniwitness.go

This PR changes the strategy for feeding logs to use a worker/jobs approach, allowing the operator to limit the number of concurrent feeders.

Use a limited number of workers for feeding

---

cmd/gcp/omniwitness/main.go
cmd/gcp/omniwitness/persistence.go
cmd/gcp/omniwitness/persistence_test.go
internal/config/log.go
omniwitness/configs.go
omniwitness/configs_test.go

This PR adds support for using public witness network configs to OmniGCP.
Towards #386 and #425

Add initial support for public witness network configuration
